# prompt_config.yaml
# Actually, default param are defined in the func in `generate_prompt.py`
default:
  prompt:
    art_style: "Soft color palette, detailed line art in modern animation style"
    gender: "Female"
    age: "20 years old"
    eye: "Dark Brown"
    hair: "Medium wavy hair, caramel brown, with detailed hair accessories"
    pose: "Gentle hand gestures picking flowers"
    expression: "Smiling happily, pay attention to the subtle shading of the expression"
    gaze: "Gently toward the flower held in hand"
    clothing: "Spring-like floral dress, focusing on flower embroidery and frill details"
    composition: "Capturing the full body of a child in a flower field while also expressing the surrounding nature in detail"
    scene: "Relaxed flower field under spring sunshine, with each surrounding flower carefully depicted"
  tweet_text: tweet text. include hash tag, text, etc

silver:
  prompt:
    eye: "Red"
    hair: "silver hair in a half-updo pulled to the side"
    pose: "waking happily on the sidewalk"
    expression: "Smiling happily, pay attention to the subtle shading of the expression"
    clothing: "An outfit resembling business casual for a new employee"
  tweet_text: "Generated By #DALLE3 #AI #AIart #AIイラスト #銀髪"

gold:
  prompt:
    eye: "Sky blue"
    hair: "light lemon yellow hair in a half-updo pulled to the side"
    pose: "waking happily on the sidewalk"
    expression: "Smiling happily, pay attention to the subtle shading of the expression"
    clothing: "An outfit resembling business casual for a new employee"
  tweet_text: "Generated By #DALLE3 #AI #AIart #AIイラスト #金髪"

red:
  prompt:
    eye: "Aquamarine blue"
    hair: "scarlet hair in a half-updo pulled to the side"
    pose: "waking happily on the sidewalk"
    expression: "Smiling happily, pay attention to the subtle shading of the expression"
    clothing: "An outfit resembling business casual for a new employee"
  tweet_text: "Generated By #DALLE3 #AI #AIart #AIイラスト #赤髪"
