# prompt_config.yaml
# Actually, default param are defined in the func in `generate_prompt.py`
default:
  prompt:
    art_style: "Soft color palette, detailed line art in modern animation style"
    gender: "Female"
    age: "20 years old"
    eye: "Dark Brown"
    hair: "Medium wavy hair, caramel brown, with detailed hair accessories"
    pose: "Gentle hand gestures picking flowers"
    expression: "Smiling happily, pay attention to the subtle shading of the expression"
    gaze: "Gently toward the flower held in hand"
    clothing: "Spring-like floral dress, focusing on flower embroidery and frill details"
    composition: "an anime-style illustration with a strong emphasis on elegance and fantasy aesthetics. The character has large, expressive eyes, a hallmark of anime art, and her features are delicate and idealized. The coloring is soft and detailed, with a pastel palette that enhances the dreamlike atmosphere. The setting is lush with vividly rendered hydrangeas in various shades, contributing to a romantic and serene mood. The character’s elaborate dress and accessories, including floral motifs and lace, reflect a rococo or victorian-inspired fantasy style, often seen in bishoujo (beautiful girl) illustrations. Overall, the image combines elements of anime, fantasy fashion, and floral art to create an ethereal and graceful visual"
    scene: "Relaxed flower field under spring sunshine, with each surrounding flower carefully depicted"
  tweet_text: tweet text. include hash tag, text, etc

silver:
  prompt:
    eye: "Red"
    hair: "Silver hair low-tied at side of head with detailed hair accessories"
    pose: "Excitedly playing on a sunny beach"
    expression: "Cheerful smile full of joy"
    gaze: "Looking toward the viewer"
    composition: "Focusing on a girl having fun on the beach"
    clothing: "A black bikini with white frills and small white polka dots, worn with a pareo covering the lower body; modest and not very revealing overall"
    scene: "A clear, bright seaside under a blue sky with gentle waves"
  tweet_text: "Generated By DALLE3 #AIart #銀髪"

gold:
  prompt:
    eye: "Sky blue"
    hair: "Light lemon yellow hair low-tied at side of head with detailed hair accessories"
    pose: "Excitedly playing on a sunny beach"
    expression: "Cheerful smile full of joy"
    gaze: "Looking toward the viewer"
    composition: "Focusing on a girl having fun on the beach"
    clothing: "A yellow bikini with white frills and small black polka dots, worn with a pareo covering the lower body; modest and not very revealing overall"
    scene: "A clear, bright seaside under a blue sky with gentle waves"
  tweet_text: "Generated By DALLE3 #AIart #金髪"

red:
  prompt:
    eye: "Aquamarine blue"
    hair: "Scarlet hair low-tied at side of head with detailed hair accessories"
    pose: "Excitedly playing on a sunny beach"
    expression: "Cheerful smile full of joy"
    gaze: "Looking toward the viewer"
    composition: "Focusing on a girl having fun on the beach"
    clothing: "A red bikini with pink frills and small white polka dots, worn with a pareo covering the lower body; modest and not very revealing overall"
    scene: "A clear, bright seaside under a blue sky with gentle waves"
  tweet_text: "Generated By DALLE3 #AIart #赤髪"
