# prompt_config.yaml
# Actually, default param are defined in the func in `generate_prompt.py`
default:
  prompt:
    art_style: "Soft color palette, detailed line art in modern animation style"
    gender: "Female"
    age: "20 years old"
    eye: "Dark Brown"
    hair: "Medium wavy hair, caramel brown, with detailed hair accessories"
    pose: "Gentle hand gestures picking flowers"
    expression: "Smiling happily, pay attention to the subtle shading of the expression"
    gaze: "Gently toward the flower held in hand"
    clothing: "Spring-like floral dress, focusing on flower embroidery and frill details"
    composition: "Capturing the full body of a child in a flower field while also expressing the surrounding nature in detail"
    scene: "Relaxed flower field under spring sunshine, with each surrounding flower carefully depicted"
  tweet_text: tweet text. include hash tag, text, etc

silver:
  prompt:
    eye: "Red"
    hair: "Long wavy silver hair with detailed hair accessories"
    pose: "Sitting and hold flowers"
    expression: "Mysterious smiling, pay attention to the subtle shading of the expression"
    clothing: "Spring-like floral dress like a fairy, focusing on flower embroidery and frill details"
    composition: "Focusing on a woman sitting and Ecstatic smiling with flowers"
    scene: "Relaxed flower field under spring sunshine, with each surrounding flower mainly lily of the valley(Suzuran) carefully depicted"
  tweet_text: "Generated By DALLE3 #AIart #銀髪"

gold:
  prompt:
    eye: "Sky blue"
    hair: "Long wavy light lemon yellow with detailed hair accessories"
    expression: "Smiling happily, pay attention to the subtle shading of the expression"
    clothing: "Spring-like floral dress like a fairy, focusing on flower embroidery and frill details"
    scene: "Relaxed flower field under spring sunshine, with each surrounding flower mainly Hypericum ascyron carefully depicted"
  tweet_text: "Generated By DALLE3 #AIart #金髪"

red:
  prompt:
    eye: "Aquamarine blue"
    hair: "Long wavy scarlet hair with detailed hair accessories"
    expression: "Smiling happily, pay attention to the subtle shading of the expression"
    clothing: "Spring-like floral dress like a fairy, focusing on flower embroidery and frill details"
    scene: "Relaxed flower field under spring sunshine, with each surrounding flower mainly Carnation carefully depicted"
  tweet_text: "Generated By DALLE3 #AIart #赤髪"
